version: '3.5'

services:
  mysql:
    hostname: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=DB
    networks:
      - test-net

  employee-backend:
    container_name: football-manager
    image: football-manager-backend:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE : docker
    networks:
      - test-net

networks:
  test-net:
    driver: bridge