version: '3.5'

services:
  mysql:
    hostname: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=citizix_user
      - MYSQL_DATABASE=citizix_db
    networks:
      - test-net

  employee-backend:
    container_name: employee-backend
    image: employee-backend:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE : docker
    networks:
      - test-net

networks:
  test-net:
    driver: bridge